/**
 * Enforces 301 redirects before static assets (legacy paths + explanation typos).
 * Generated by scripts/generate-redirects.js — do not edit by hand.
 */
const EXACT = new Map([
  ['/programmatic/how-much-chlorine-for-5000-gallon-pool', '/programmatic/chlorine/how-much-chlorine-for-5000-gallon-pool'],
  ['/programmatic/how-much-chlorine-for-10000-gallon-pool', '/programmatic/chlorine/how-much-chlorine-for-10000-gallon-pool'],
  ['/programmatic/how-much-chlorine-for-15000-gallon-pool', '/programmatic/chlorine/how-much-chlorine-for-15000-gallon-pool'],
  ['/programmatic/how-much-chlorine-for-20000-gallon-pool', '/programmatic/chlorine/how-much-chlorine-for-20000-gallon-pool'],
  ['/programmatic/explanation/why-ph-affects-chlorine', '/programmatic/explanations/why-ph-affects-chlorine'],
  ['/explanations/why-ph-affects-chlorine', '/programmatic/explanations/why-ph-affects-chlorine'],
  ['/programmatic/explanation/what-is-pool-alkalinity', '/programmatic/explanations/what-is-pool-alkalinity'],
  ['/explanations/what-is-pool-alkalinity', '/programmatic/explanations/what-is-pool-alkalinity'],
  ['/programmatic/explanation/why-shower-before-pool', '/programmatic/explanations/why-shower-before-pool'],
  ['/explanations/why-shower-before-pool', '/programmatic/explanations/why-shower-before-pool'],
  ['/calculators/volume-calculator', '/calculators/pool-volume-calculator'],
  ['/charts/hot-tub-chemical-levels-chart', '/hot-tub-chemical-levels-chart'],
  ['/charts/pool-chemical-levels-chart', '/pool-chemical-levels-chart'],
  ['/printables/pool-maintenance-checklist', '/resources/pool-maintenance-checklist'],
  ['/printables/hot-tub-maintenance-log', '/resources/hot-tub-maintenance-log'],
  ['/printables/airbnb-pool-turnover-checklist', '/resources/airbnb-pool-turnover-checklist']
]);

function normalizePath(pathname) {
  let p = pathname;
  if (p.length > 1 && p.endsWith('/')) p = p.slice(0, -1);
  if (p.endsWith('.html')) p = p.slice(0, -5);
  return p;
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const path = normalizePath(url.pathname);
  const dest = EXACT.get(path);
  if (dest) {
    return Response.redirect(url.origin + dest, 301);
  }
  if (path.startsWith('/programmatic/explanation/')) {
    const rest = path.slice('/programmatic/explanation'.length);
    return Response.redirect(url.origin + '/programmatic/explanations' + rest, 301);
  }
  if (path.startsWith('/explanations/')) {
    const rest = path.slice('/explanations'.length);
    return Response.redirect(url.origin + '/programmatic/explanations' + rest, 301);
  }
  return context.next();
}
